# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ColShare
email: info@ycolshare.com
description: ColShare is a blog where youth share their thought and any one with good advice
baseurl: "/colshare" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ColShare
github_username:  shyakadev
repository: "shyakadev/youthot"
# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/


# Sass stylesheet
sass:
    style: compressed

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

#footer
built-by: ST
copyright:
    name: ColShare
    link: '#'
